<<<<<<< HEAD
# Generated by Django 3.1.5 on 2021-03-26 21:33
=======
# Generated by Django 3.1.7 on 2021-03-27 05:20
>>>>>>> 71ba2e2cb0db1ecbbb0b49d7e0f34c3d10a16946

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='')),
                ('logged', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=100)),
<<<<<<< HEAD
                ('phoneNumber', models.IntegerField()),
=======
                ('phoneNumber', models.IntegerField(null=True)),
>>>>>>> 71ba2e2cb0db1ecbbb0b49d7e0f34c3d10a16946
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
